### ISSUE TITLE
Require Date.js

### ISSUE THREAD

**Issue by michaelparenteau** [caarlos0/bootstrap-daterangepicker-rails#1]
Maybe I am missing something, but I tried to use this gem with your README documentation along with the docs on the bootstrap-daterangepicker blog post... and when calling `$('#element').daterangepicker()` like in the simple example, I get:

```
TypeError: 'undefined' is not a function (evaluating 'Date.today()')
```

Seems like that stuff was supposed to be defined in Date.js which I don't see in the dependencies, vendor/assets/javascripts directory, nor is it being loaded in the app from elsewhere.

Are we supposed to include that on our own? If so, can we update the README to say something about that? I would be happy to fork and submit documentation pull requests if you don't want to update the Gem to include another javascript file.

**Comment by caarlos0** [comment]
@michaelparenteau sorry I'm late, I completely lost this issue...
